### ISSUE TITLE
楼主，我是用你的多图片上传，目前是后台只收到一张图片

### ISSUE THREAD

**Issue by Dreamer206602** [lidong1665/Android-UploadMultipartImage#1]
Map<String,RequestBody>params2=new HashMap<>();
                    for (int i = 0; i <imgPaths.size() ; i++) {
                        params2.put("image\"; filename=\"icon.jpg",
                                RequestBody.create(MediaType.parse("multipart/form-data"),
                                        new File(imgPaths.get(i))));
                    }

**Comment by lidong1665** [comment]
我用的struts2可以的

**Comment by charlidsun** [comment]
photos.put("file\"; filename=\"image.png" + a[i], RequestBody.create(MediaType.parse("multipart/form-data"), new File(paths.get(i))));
定义了一个数组，这样他们的map的key就不唯一了，然后传给后台，后台File数组接收到参数跟photos这个map的size是一样的。多图片上传的功能就实现了。
